/**
 * PR-D2 — Durable upload metadata store.
 *
 * Previously, upload entries (uploadId → extractedDir) lived only in a
 * server-side in-process Map. A process restart between the POST /upload/archive
 * request and the POST /projects/discover request silently dropped the entry,
 * causing ARCHIVE_UPLOAD discovery to fail with a misleading "Upload not found
 * or expired" error.
 *
 * Moving metadata to the DB means the entry survives restarts. The extracted
 * files themselves stay in /tmp (they survive process restarts on Linux since
 * /tmp is a tmpfs that is not wiped between process starts, only on host reboot).
 * If a restart happens to be a full host reboot and the extracted dir is gone,
 * the ARCHIVE_UPLOAD adapter detects the missing dir on lookup and returns a
 * clear "re-upload required" error — no silent failure.
 */
import { pgTable, text, timestamp, index } from "drizzle-orm/pg-core";

export const uploadsTable = pgTable(
  "uploads",
  {
    /** The uploadId returned to the client. UUID generated by the upload route. */
    id: text("id").primaryKey(),

    /** Clerk user ID of the uploader. Enforced at the route level (requireAuth). */
    ownerId: text("owner_id").notNull(),

    /** Absolute path of the extracted directory on the server filesystem. */
    extractedDir: text("extracted_dir").notNull(),

    /** Original filename of the uploaded archive (for logging and UI display). */
    originalName: text("original_name").notNull(),

    /** When the upload was registered. */
    createdAt: timestamp("created_at").notNull().defaultNow(),

    /**
     * When this entry expires. Set to createdAt + TTL at insert time.
     * The periodic sweep and the startup reconciliation delete rows past
     * this timestamp and remove their extracted directories.
     * Default TTL: 1 hour.
     */
    expiresAt: timestamp("expires_at").notNull(),
  },
  (t) => [
    index("idx_uploads_owner_id").on(t.ownerId),
    index("idx_uploads_expires_at").on(t.expiresAt),
  ],
);

export type InsertUpload = typeof uploadsTable.$inferInsert;
export type Upload = typeof uploadsTable.$inferSelect;
