export { setBaseUrl, setAuthTokenGetter, ApiError, customFetch } from "./custom-fetch";
export type { AuthTokenGetter, CustomFetchOptions, ErrorType } from "./custom-fetch";
export {
  classifyProjectError,
  isRetryableProjectError,
  emitProjectLoadFailed,
} from "./project-error";
export type {
  ProjectErrorKind,
  ProjectLoadFailure,
  ProjectLoadFailedContext,
} from "./project-error";
// PR-I: handwritten SSE hook — not generated by Orval
export { useAiChatStream } from "./use-ai-chat-stream";
export type {
  AiChatStreamParams,
  AiChatStreamCallbacks,
  AiStreamEvent,
  AiStreamStageEvent,
  AiStreamDeltaEvent,
  AiStreamDoneEvent,
  AiStreamErrorEvent,
} from "./use-ai-chat-stream";
export * from './generated/api';
export * from './generated/api.schemas';
