export { setBaseUrl, setAuthTokenGetter, ApiError, customFetch } from "./custom-fetch";
export type { AuthTokenGetter, CustomFetchOptions, ErrorType } from "./custom-fetch";
export {
  classifyProjectError,
  isRetryableProjectError,
  emitProjectLoadFailed,
} from "./project-error";
export type {
  ProjectErrorKind,
  ProjectLoadFailure,
  ProjectLoadFailedContext,
} from "./project-error";
// PR-I: handwritten SSE hook — not generated by Orval
export { useAiChatStream, useAiTaskStream, parseValidationEvent, processAiStream } from "./use-ai-chat-stream";
export type {
  AiChatStreamParams,
  AiChatStreamCallbacks,
  AiTaskStreamParams,
  AiTaskStreamCallbacks,
  AiStreamEvent,
  AiStreamStageEvent,
  AiStreamDeltaEvent,
  AiStreamDoneEvent,
  AiStreamExecutionNodesEvent,
  AiStreamRecipeNodeProgressEvent,
  AiStreamCapabilityGapEvent,
  RecipeNodeState,
  CapabilityGap,
  AiExecutionNodeSnapshot,
  AiExecutionNodeStatus,
  AiBehaviorEvidence,
  AiStreamErrorEvent,
  AiStreamResetEvent,
  AiStreamToolCallEvent,
  AiStreamToolResultEvent,
  AiStreamValidationEvent,
  AiStreamRepairStateEvent,
  RepairLoopState,
  AiStreamThinkingEvent,
  AiStreamExecutionGuardEvent,
  AiStreamSynthesisStartEvent,
  AiStreamExecutionDiagnosticEvent,
  AiStreamEvidenceIntegrityEvent,
  AiStreamExecutionSummary,
  AiSemanticTraceSourceSpan,
  AiSemanticTraceNode,
  AiSemanticTraceEdge,
  AiCrossFileSemanticTrace,
  AiProductionReachabilityTrace,
  AiStreamProductionTraceEvent,
  AiStreamCrossFileTraceEvent,
  AiStreamTaskStartedEvent,
  AiStreamTaskProgressEvent,
  AiStreamTaskDoneEvent,
} from "./use-ai-chat-stream";
export * from './generated/api';
export * from './generated/api.schemas';
